name: Run Maven tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [3.2.17]
        java-version: [1.8]

    steps:
    - name: Install and Start MongoDB
      run: |
        wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${{ matrix.mongodb-version }}.tgz
        tar xfz mongodb-linux-x86_64-${{ matrix.mongodb-version }}.tgz
        export PATH=`pwd`/mongodb-linux-x86_64-${{ matrix.mongodb-version }}/bin:$PATH
        mkdir -p data/db
        mongod --dbpath=data/db &
        mongod --version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
        java-version: ${{ matrix.java-version }}
    - name: Run Maven tests
      run: mvn test
